language: cpp

sudo: required

os:
  - linux
#  - osx

env:
  - CONFIG=Release
#  - CONFIG=Debug

services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/

install:
  - ./scripts/travisciinstall

script:
  - ./scripts/travisciscript

notifications:
  email: team@opencor.ws
