# Note: brew doesn't yet support Qt 5.5, so we disable testing on OS X for
#       now...
#       (see https://github.com/Homebrew/homebrew/blob/master/Library/Formula/qt5.rb)

language: cpp

os:
#  - linux
  - osx

env:
#  - CONFIG=Release
  - CONFIG=Debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-i386.tar.gz
      && tar -xzf cmake-3.2.3-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.2.3-Linux-i386/* /usr
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt55
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt55location qt55multimedia qt55sensors qt55svg qt55tools qt55webkit
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  # Note #1: the PPA that we use on Linux relies on Travis CI's version of the
  #          ICU libraries, so we need to let CMake know about it...
  # Note #2: Travis CI uses Ubuntu 12.04 LTS while we use Ubuntu 14.04 LTS, and
  #          this causes problems when we try to use our prebuilt version of
  #          libgit2 (because of its need of libc). So, to 'fix' this, we ask
  #          for libgit2 to be built on Linux...
  -    cd build
    && if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         cmake -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/opt/qt55/lib/cmake -DUSE_PREBUILT_LIBGIT2_PLUGIN=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON ..
         ;
       else
         cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON ..
         ;
       fi
    && make -j 3
    && cd ..
    && for i in `find build/OpenCOR.app/Contents -type f`; do otool -L $i; done | grep -v "is not an object file"
    && ./run -c CellMLTools::help
    && if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         build/bin/runtests
         ;
       else
         build/OpenCOR.app/Contents/MacOS/runtests
         ;
       fi

notifications:
  email:
    - team@opencor.ws
    - agarny@hellix.com
