language: cpp

os:
  - linux
#  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

before_install:
  -    sudo apt-get install libc6-i386
    && wget http://www.cmake.org/files/v3.0/cmake-3.0.0-Linux-i386.tar.gz
    && tar -xzf cmake-3.0.0-Linux-i386.tar.gz
  -    sudo apt-add-repository -y ppa:beineri/opt-qt53
    && sudo apt-get -qq update
    && sudo apt-get -qq install cmake
    && sudo apt-get -qq install qt53tools qt53svg qt53webkit
  -    PROCS=`cat /proc/cpuinfo | grep processor | wc -l`
    && export JOBS=`echo "$PROCS-$PROCS/2" | bc`

script:
  -    export PATH=/home/travis/build/opencor/opencor/cmake-3.0.0-Linux-i386/bin:$PATH
    && cd build
    && which cmake
    && ldd /home/travis/build/opencor/opencor/cmake-3.0.0-Linux-i386/bin/cmake
    && ls -l /home/travis/build/opencor/opencor/cmake-3.0.0-Linux-i386/bin/cmake
    && cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/opt/qt53/lib/cmake -DENABLE_TESTS=True ..
    && echo $JOBS
    && make -j $JOBS
    && cd tests
    && ./runtests -platform offscreen

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - team@opencor.ws
      - agarny@hellix.com
