language: cpp

sudo: required

os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker build -f scripts/traviscilinuxinstall -t travis-ci .
      ;
    else
         brew update
      && brew install ninja qt@5.9.2
      && chmod -R 755 /usr/local/opt/qt/*
      && export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker run -e CONFIG=$CONFIG -it travis-ci scripts/traviscilinuxscript
      ;
    else
         cd build
      && cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..
      && ninja
      && OpenCOR.app/Contents/MacOS/runtests
      ;
    fi

notifications:
  email: team@opencor.ws
