language: cpp

os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

before_install:
  - if [ "`uname -s`" = "Linux" ]; then
         sudo apt-get -qq update
      && sudo apt-get -qq install libc6-i386
      && wget http://www.cmake.org/files/v3.0/cmake-3.0.0-Linux-i386.tar.gz
      && tar -xzf cmake-3.0.0-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.0.0-Linux-i386/* /usr
    else
         curl -O http://www.cmake.org/files/v3.0/cmake-3.0.0-Darwin-universal.tar.gz
      && tar -xzf cmake-3.0.0-Darwin-universal.tar.gz
      && sudo cp -fR cmake-3.0.0-Darwin-universal/CMake.app/Contents/* /usr
    fi
  - if [ "`uname -s`" = "Linux" ]; then
         sudo apt-add-repository -y ppa:beineri/opt-qt53 \
      && sudo apt-get -qq update \
      && sudo apt-get -qq install qt53tools qt53svg qt53webkit
    else
         brew update \
      && brew install qt5
    fi

script:
  - if [ "`uname -s`" = "Linux" ]; then
         cd build \
      && cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/opt/qt53/lib/cmake -DENABLE_TESTS=True .. \
      && make -j `cat /proc/cpuinfo | grep processor | wc -l` \
      && cd tests \
      && ./runtests -platform offscreen
    else
         cd build \
      && cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_TESTS=True .. \
      && make -j `sysctl hw.ncpu | cut -d " " -f 2` \
      && cd tests \
      && ./runtests -platform offscreen
    fi

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - team@opencor.ws
      - agarny@hellix.com
