language: cpp

compiler:
  - gcc
  - clang

env:
  - CONFIG=Release
  - CONFIG=Debug

before_install:
  - export JOBS=`cat /proc/cpuinfo | grep processor | wc -l`
  - sudo apt-get -qq update
  - sudo apt-get -qq install ia32-libs
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12-Linux-i386.sh
  - chmod +x cmake-2.8.12-Linux-i386.sh
  - sudo ./cmake-2.8.12-Linux-i386.sh --skip-license --prefix=/usr
  - cmake --version
  - sudo apt-get -qq update
  - sudo apt-get -qq install libgl1-mesa-dev
  - sudo apt-add-repository -y ppa:beineri/opt-qt511
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt51base qt51svg

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_PREFIX_PATH=/opt/qt51/lib/cmake -DENABLE_TESTING=True ..
  - make -j $JOBS
  - cd tests
  - ./runtests

notifications:
  recipients: team@opencor.ws
  email:
    on_success: change
    on_failure: always
