language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - JOBS=4
  matrix:
    - CONFIG=Release
    - CONFIG=Debug

before_install:
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
  - tar xf cmake-2.8.12.tar.gz
  - cd cmake-2.8.12
  - ./configure --parallel=$JOBS --prefix=/usr
  - make -j $JOBS
  - sudo make install
  - cd ..
  - cmake --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgl1-mesa-dev
  - sudo apt-add-repository -y ppa:beineri/opt-qt511
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt51base

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_PREFIX_PATH=/opt/qt51/lib/cmake -DENABLE_TESTING=True ..
  - make -j $JOBS
  - cd tests
  - ./runtests

notifications:
  recipients: team@opencor.ws
  email:
    on_success: change
    on_failure: always
