language: cpp

sudo: required

os:
  - linux
#  - osx

env:
  - CONFIG=Release
#  - CONFIG=Debug

services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         docker pull ubuntu:16.04
      && docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/iqrfsdk -td ubuntu:16.04 /bin/bash
      && docker exec -ti travis-ci bash -c "apt-get install -y software-properties-common"
      && docker exec -ti travis-ci bash -c "add-apt-repository -y ppa:beineri/opt-qt562-xenial"
      && docker exec -ti travis-ci bash -c "apt -qq update"
      && docker exec -ti travis-ci bash -c "apt -qq install g++-5 libgl1-mesa-dev libglu1-mesa-dev ninja-build"
      && docker exec -ti travis-ci bash -c "apt -qq install qt56location qt56multimedia qt56sensors qt56svg qt56tools qt56webchannel"
      ;
    else
         brew update
      && curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/106d0878ee812cb8f5c403f717bdebe836445aee/Formula/qt5.rb
      && brew install ./qt5.rb ninja
      && export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  -    cd build
    && if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/opt/qt56/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON..
         ;
       else
         cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..
         ;
       fi
    && ninja
    && cd ..
    && if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         build/bin/OpenCOR -a
         ;
       else
         build/OpenCOR.app/Contents/MacOS/runtests
         ;
       fi

notifications:
  email: team@opencor.ws
