language: cpp

sudo: required

os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker build -f scripts/traviscilinuxinstall -t travis-ci .
      ;
    else
         brew update
      && curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/5d2e2fdebc5c5a04787a01cf0197b179dbf7a994/Formula/qt.rb
      && brew install ./qt.rb ninja
      && export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker run -e CONFIG=$CONFIG -it travis-ci scripts/traviscilinuxscript
      ;
    else
         cd build
      && cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..
      && ninja
      && OpenCOR.app/Contents/MacOS/runtests
      ;
    fi

notifications:
  email: team@opencor.ws
