language: cpp

env:
  - CONFIG=Release
  - CONFIG=Debug

before_install:
  -    sudo apt-add-repository -y ppa:beineri/opt-qt53
    && sudo apt-get -qq update
    && sudo apt-get -qq install cmake
    && wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
    && tar -xzf cmake-2.8.12.2.tar.gz
    && cd cmake-2.8.12.2
    && mkdir build
    && cd build
    && cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    && export PROCS=`cat /proc/cpuinfo | grep processor | wc -l`
    && make -j `echo "$PROCS-$PROCS/2" | bc`
    && sudo make install
    && cd ../..
    && sudo apt-get -qq install qt53tools qt53svg qt53webkit

script:
  -    cd build
    && cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/opt/qt53/lib/cmake -DENABLE_TESTS=True ..
    && make -j $PROCS
    && cd tests
    && ./runtests -platform offscreen

notifications:
  recipients:
    - team@opencor.ws
    - agarny@hellix.com
  email:
    on_success: change
    on_failure: always
