branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

os: unstable

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

install:
  - if "%PLATFORM%" EQU "x86" ( set QTDIR=C:\Qt\5.4\msvc2013_opengl ) else ( set QTDIR=C:\Qt\5.4\msvc2013_64_opengl )
  - set PATH=C:\CMake\bin;%QTDIR\bin%;C:\Qt\Tools\QtCreator\bin;%PATH%
  - appveyor DownloadFile "http://www.cmake.org/files/v3.1/cmake-3.1.2-win32-x86.exe" -FileName cmakesetup.exe
  - cmakesetup /S /D=C:\CMake
  - if "%PLATFORM%" EQU "x86" ( call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\vcvars32.bat" ) else ( call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\vcvarsx86_amd64.bat" )

build_script:
  - cd build
  - cmake -G "NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_PREFIX_PATH=%QTDIR%\lib\cmake -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON ..
  - jom
  - cd ..

test_script:
  - build\bin\runtests

on_failure:
  - dir  C:\projects\opencor\build\CMakeFiles\CMakeTmp /s
  - type "C:\projects\opencor\build\CMakeFiles\CMakeOutput.log"
  - type "C:\projects\opencor\build\CMakeFiles\CMakeError.log"

notifications:
  - provider: Email
    to:
      - team@opencor.ws
      - agarny@hellix.com
    on_build_status_changed: true
