branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

os: unstable

environment:
  CMAKEROOTDIR: C:\CMake
  QTDIR: C:\Qt\5.4\msvc2013_64_opengl\bin

matrix:
  fast_finish: false
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

install:
  - set PATH=%CMAKEROOTDIR%\bin;%QTDIR%;%PATH%
  - appveyor DownloadFile "http://www.cmake.org/files/v3.1/cmake-3.1.2-win32-x86.exe" -FileName cmakesetup.exe
  - cmakesetup /S /D=%CMAKEROOTDIR%

build_script:
  - cd build
  - cmake -G "NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DENABLE_TESTS=ON ..
  - jom
  - cd ..

test_script:
  - build\bin\runtests

on_failure:
  - dir  C:\projects\opencor\build\CMakeFiles\CMakeTmp /s
  - type "C:\projects\opencor\build\CMakeFiles\CMakeOutput.log"
  - type "C:\projects\opencor\build\CMakeFiles\CMakeError.log"

notifications:
  - provider: Email
    to:
      - team@opencor.ws
      - agarny@hellix.com
    on_build_status_changed: true
