branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

os: unstable

install:
  - dir c:\Qt
  - dir c:\Qt\5.4
  - cmake --version
  - qmake --version

build_script:
  - maketests

test_script:
  - runtests

notifications:
  - provider: Email
    to:
      - team@opencor.ws
      - agarny@hellix.com
    on_build_status_changed: true
