branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

os: unstable

install:
  - set PATH=%PATH%;C:\Qt\5.4\msvc2013\bin
  - cmake --version
  - qmake --version
  - ninja --version

build_script:
  - maketests

test_script:
  - runtests

notifications:
  - provider: Email
    to:
      - team@opencor.ws
      - agarny@hellix.com
    on_build_status_changed: true
