branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

os: unstable

environment:
  CMAKEROOTDIR: C:\CMake
  QTDIR: C:\Qt\5.4\msvc2013_64_opengl\bin

install:
  - set PATH=%CMAKEDIR%\bin;%QTDIR%;%PATH%
  - cmake --version
  - qmake --version
  - appveyor DownloadFile "http://www.cmake.org/files/v3.1/cmake-3.1.2-win32-x86.exe" -FileName cmakesetup.exe
  - cmakesetup /S /D=%CMAKEDIR%
  - cmake --version

build_script:
  - maketests

test_script:
  - runtests

notifications:
  - provider: Email
    to:
      - team@opencor.ws
      - agarny@hellix.com
    on_build_status_changed: true
