branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

install:
  - dir c:\ /s

build_script:
  - maketests

test_script:
  - runtests

notifications:
  - provider: Email
    to:
      - team@opencor.ws
      - agarny@hellix.com
    on_build_status_changed: true
