name: cd

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  cd:
    name: OpenCOR's user documentation
    if: ${{ github.event.head_commit.message == 'New snapshot.' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out OpenCOR
        uses: actions/checkout@v2
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install packages
        run: sudo apt install python3-sphinx
      - name: Generate OpenCOR's user documentation
        run: ./cd
      - name: Deploy OpenCOR's user documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: opencor/opencor.github.io
          publish_branch: master
          publish_dir: build/opencor-user-documentation/build/html
