name: cd

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  cd:
    name: OpenCOR's documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out OpenCOR
        uses: actions/checkout@v2
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install packages
        run: sudo apt install python3-sphinx
      - name: Generate OpenCOR's documentation
        run: ./cd
      - name: Deploy OpenCOR's documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: opencor/opencor.github.io
          publish_branch: master
          publish_dir: build/doc/html
